#!/bin/bash -xeu

function write_service_account_key() {
  set +x
  if [ ! -f "${BBL_GCP_SERVICE_ACCOUNT_KEY}" ]; then
    echo "${BBL_GCP_SERVICE_ACCOUNT_KEY}" > /tmp/google_service_account.json
    export BBL_GCP_SERVICE_ACCOUNT_KEY="/tmp/google_service_account.json"
  fi
  set -x
}

function main() {

	pwd
	ls
	ls ../
	ls ../..

	echo ${BBL_IAAS}
	echo ${BBL_GCP_SERVICE_ACCOUNT_KEY}
	echo ${BBL_GCP_PROJECT_ID}
	echo ${BBL_GCP_ZONE}
	echo ${BBL_GCP_REGION}
	echo ${BBL_STATE_DIR}
	echo ${BBL_LB_CERT}
	echo ${BBL_LB_KEY}
	echo ${LB_DOMAIN}
	echo ${BBL_ENV_NAME}
	cat ${BBL_GCP_SERVICE_ACCOUNT_KEY}
	
    bbl --debug up --iaas gcp --gcp-project-id concourse-sandbox --gcp-service-account-key bbl-state/google_account_creds.json --gcp-region europe-west1 --gcp-zone europe-west1-b > bbl_up.txt
}

main ${PWD}
