#!/bin/bash -xeu

function check_fast_fails() {
  set +x
  if [ -z "${LB_DOMAIN}" -a "${BBL_IAAS}" == "gcp" ]; then
    echo "\$LB_DOMAIN is a required parameter for gcp.  Please set the domain."
    exit 1
  fi

  if [ -z "${BBL_LB_CERT}"  ]; then
    echo "\$BBL_LB_CERT is a required parameter"
    exit 1
  fi

  if [ -z "${BBL_LB_KEY}"  ]; then
    echo "\$BBL_LB_KEY is a required parameter"
    exit 1
  fi

  if [ -n "${LB_DOMAIN}" -a "${BBL_IAAS}" == "aws" ]; then
    echo "\$LB_DOMAIN is not honored for aws"
  fi
  set -x
}

function write_bbl_certs() {
  set +x
  if [ ! -f "${BBL_LB_CERT}" ]; then
    echo "$BBL_LB_CERT" > /tmp/bbl-cert
    bbl_cert_path="/tmp/bbl-cert"
  else
    bbl_cert_path="${BBL_LB_CERT}"
  fi
  if [ ! -f "${BBL_LB_KEY}" ]; then
    echo "$BBL_LB_KEY" > /tmp/bbl-key
    bbl_key_path="/tmp/bbl-key"
  else
    bbl_key_path="${BBL_LB_KEY}"
  fi
  set -x
}

function main() {

	check_fast_fails
	
	#pushd "bbl-state/${BBL_STATE_DIR}"
	  local bbl_cert_path
      local bbl_key_path
      write_bbl_certs
	  
	  bbl version
      
	  pwd
	  ls
	  ls ../
	  ls ../..
      
	  echo ${BBL_IAAS}
	  echo ${BBL_GCP_SERVICE_ACCOUNT_KEY}
	  echo ${BBL_GCP_PROJECT_ID}
	  echo ${BBL_GCP_ZONE}
	  echo ${BBL_GCP_REGION}
	  echo ${BBL_STATE_DIR}
	  echo ${BBL_LB_CERT}
	  echo ${BBL_LB_KEY}
	  echo ${LB_DOMAIN}
	  echo ${BBL_ENV_NAME}
	  cat ${BBL_GCP_SERVICE_ACCOUNT_KEY}
	  
      bbl --debug up
	#popd
}

main ${PWD}
